### ISSUE TITLE
"Export" Error. 'Uncaught SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by beaudevanney** [MarkRoss470/blooket#1]
let allBlooks = {
            Chick: "https://blooket.s3.us-east-2.amazonaws.com/blooks/farmAnimals/chick.svg",
             ...
            "King of Hearts": "https://blooket.s3.us-east-2.amazonaws.com/blooks/wonderland/kingOfHearts.svg",
};
**export {allBlooks};**
(also note that this is happening for every one. Plz fix)

**Comment by MarkRoss470** [comment]
This is because that javascript file is a module. This works as intended if you use the project as a chrome extension as described in the installation section of the repo's readme, which also provides a graphical interface for adding gold and changing blooks. If you would like to use the code in a different way to this, you will need to either refactor the code to not use modules (there exist javascript bundlers for this purpose) or provide more details on your use case so that I can make changes to the codebase to support it.
