### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ThikBoiYT** [MarkRoss470/blooket#2]
which part do we need to copy for add tokens
all?

**Comment by MarkRoss470** [comment]
This is not a script, it's a browser extension. If you're using chrome or a chromium based browser, follow the instructions in the readme (scroll down from the main page). I don't know if it's possible to make this a normal js script because blooket seems to have some measures in place to stop that which doesn't apply to extensions.

**Comment by ThikBoiYT** [comment]
ok thank you

**Comment by ThikBoiYT** [comment]
you can't do it on skl computer b/c developer mode is blocked

**Comment by MarkRoss470** [comment]
Do you have sync turned on? Click on your profile icon in the top right and click 'turn on sync' if it is there, then try again.

**Comment by MarkRoss470** [comment]
Closed as inactive
